### ISSUE TITLE
Uncaught TypeError: WEBAudio.audioContext.listener.setVelocity is not a function

### ISSUE THREAD

**Issue by karthiknadig** [vilbeyli/Pacman-Clone#5]
In chrome Pacman fails to load with this error:
![image](https://cloud.githubusercontent.com/assets/3840081/26758793/30dcf9ce-489e-11e7-8a61-bb1e3fb9e716.png)

```
(index):32 run() called, but dependencies remain, so not running
printErr @ (index):32
(index):32 pre-main prep time: 100 ms
printErr @ (index):32
(index):32 Calling stub instead of signal()
printErr @ (index):32
(index):28 Initialize engine version: 5.0.1f1 (5a2e8fe35a68)
(index):28 Renderer: WebKit WebGL
(index):28 Vendor:   WebKit
(index):28 Version:  WebGL 1.0 (OpenGL ES 2.0 Chromium)
(index):28 GLES:     0
(index):28 ANGLE_instanced_arrays GL_ANGLE_instanced_arrays EXT_blend_minmax GL_EXT_blend_minmax EXT_disjoint_timer_query GL_EXT_disjoint_timer_query EXT_frag_depth GL_EXT_frag_depth EXT_shader_texture_lod GL_EXT_shader_texture_lod EXT_sRGB GL_EXT_sRGB EXT_texture_filter_anisotropic GL_EXT_texture_filter_anisotropic WEBKIT_EXT_texture_filter_anisotropic GL_WEBKIT_EXT_texture_filter_anisotropic OES_element_index_uint GL_OES_element_index_uint OES_standard_derivatives GL_OES_standard_derivatives OES_texture_float GL_OES_texture_float OES_texture_float_linear GL_OES_texture_float_linear OES_texture_half_float GL_OES_texture_half_float OES_texture_half_float_linear GL_OES_texture_half_float_linear OES_vertex_array_object GL_OES_vertex_array_object WEBGL_compressed_texture_s3tc GL_WEBGL_compressed_texture_s3tc WEBKIT_WEBGL_compressed_texture_s3tc GL_WEBKIT_WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info GL_WEBGL_debug_renderer_info WEBGL_debug_shaders GL_WEBGL_debug_shaders WEBGL_depth_texture GL_WEBGL_depth_texture
(index):28  WEBKIT_WEBGL_depth_texture GL_WEBKIT_WEBGL_depth_texture WEBGL_draw_buffers GL_WEBGL_draw_buffers WEBGL_lose_context GL_WEBGL_lose_context WEBKIT_WEBGL_lose_context GL_WEBKIT_WEBGL_lose_context
(index):28 Creating OpenGLES2.0 graphics device
(index):32 exception thrown: TypeError: WEBAudio.audioContext.listener.setVelocity is not a function,TypeError: WEBAudio.audioContext.listener.setVelocity is not a function
    at _JS_Sound_SetListenerVelocity (https://vilbeyli.github.io/Pacman/Release/webgl.js:1:296172)
    at Smf (https://vilbeyli.github.io/Pacman/Release/webgl.js:21:677283)
    at hpf (https://vilbeyli.github.io/Pacman/Release/webgl.js:21:716350)
    at Bcf (https://vilbeyli.github.io/Pacman/Release/webgl.js:21:377314)
    at rbf (https://vilbeyli.github.io/Pacman/Release/webgl.js:21:348467)
    at Array.sbf (https://vilbeyli.github.io/Pacman/Release/webgl.js:21:348849)
    at Jcf (https://vilbeyli.github.io/Pacman/Release/webgl.js:21:381781)
    at Array.Dkf (https://vilbeyli.github.io/Pacman/Release/webgl.js:21:653275)
    at yjd (https://vilbeyli.github.io/Pacman/Release/webgl.js:37:992502)
    at Array.vgg (https://vilbeyli.github.io/Pacman/Release/webgl.js:29:430369)
printErr @ (index):32
UnityConfig.js:74 Invoking error handler due to
Uncaught TypeError: WEBAudio.audioContext.listener.setVelocity is not a function
webgl.js:1 Uncaught TypeError: WEBAudio.audioContext.listener.setVelocity is not a function
    at _JS_Sound_SetListenerVelocity (webgl.js:1)
    at Smf (webgl.js:21)
    at hpf (webgl.js:21)
    at Bcf (webgl.js:21)
    at rbf (webgl.js:21)
    at Array.sbf (webgl.js:21)
    at Jcf (webgl.js:21)
    at Array.Dkf (webgl.js:21)
    at yjd (webgl.js:37)
    at Array.vgg (webgl.js:29)

```

**Comment by vilbeyli** [comment]
Hmm. It's been a while since I touched this project. I'll take a look in a few weeks and try to fix this! Thank you for letting me know.
